name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: "Debug - runner info"
        run: |
          echo "Runner: $(uname -a || hostnamectl || echo unknown)"
          node -v || echo "node not found"
          npm -v || echo "npm not found"
          ls -la

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration production --base-href /Angular-Project/

      - name: Create .nojekyll
        run: echo > ./dist/project/.nojekyll

      - name: "Debug - list dist/project"
        run: |
          echo 'Listing dist/project:'
          ls -la dist/project || true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist/project

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
