name: Test Actions Runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runner info
        run: |
          echo "Runner: $(uname -a || hostnamectl || echo unknown)"
          echo "Node: $(node -v || echo node-not-found)"
          echo "NPM: $(npm -v || echo npm-not-found)"
          ls -la
